# .github/workflows/update-commit-sha.yml new
name: Update commit_sha.txt

on:
  workflow_call:

jobs:
  update-commit-sha:
    runs-on: ubuntu-latest
    # permissions:
    #   contents: write
    #   pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
        
      - name: Append commit SHA to file
        run: |
          echo "${GITHUB_SHA}" >> commit_sha.txt
      
      - name: Configure Git
        run: |
          echo ${{ secrets.PULL_WRITE_PAT }}
          TESTMAN="tikki${{ secrets.CONTENT_PULL_WRITE_PAT }}2"
          STRING1="Hello,"
          STRING2=" World!$TESTMAN!"
          CONCATENATED="$STRING1$STRING2"
          echo "Concatenated String: $CONCATENATED"
      
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        env:
          GH_TOKEN: ${{ secrets.CONTENT_PULL_WRITE_PAT }}
        run: |
          # Set up Git
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
          # Checkout a new branch
          git checkout -b update-image-digest-${{ github.sha }}
        
          # Add changes and commit
          git add commit_sha.txt
          git commit -m "Add Docker image tag and digest [ci skip]"
        
          # Push changes to the new branch
          git push origin HEAD:update-image-digest-${{ github.sha }}
        
          # Create a pull request using GitHub CLI
          gh pr create --title "Update image digest" --body "This PR updates the Docker image digest." --head update-image-digest-${{ github.sha }} --base main
          
          # Fetch the PR number for auto-merge
          PR_NUMBER=$(gh pr list --state open --head update-image-digest-${{ github.sha }} --json number --jq '.[0].number')
        
          # Auto-merge the pull request
          gh pr merge $PR_NUMBER --merge --admin --delete-branch --body "[ci skip]"
        
             



      # - name: Commit changes
      #   run: |
      #     # git add commit_sha.txt
      #     # git commit -m "Add commit SHA ${GITHUB_SHA}"
      #     # # git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      #     # git push origin HEAD
      #       git config --global user.name 'github-actions[bot]'
      #       git config --global user.email 'github-actions[bot]@users.noreply.github.com'
      #       git checkout -b update-image-digest-${{ github.sha }}
      #       git add commit_sha.txt
      #       git commit -m "Add Docker image tag and digest [ci skip]"
      #       git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      #       git push origin HEAD:update-image-digest-${{ github.sha }}
        
      #       # Create a pull request
      #       gh pr create --title "Update image digest" --body "pr body" --head update-image-digest-${{ github.sha }} --base master
        
      #       # Auto-merge the PR and delete the branch
      #       PR_NUMBER=$(gh pr list --state open --head update-image-digest-${{ github.sha }} --json number --jq '.[0].number')
      #       gh pr merge $PR_NUMBER --merge
      #       git push origin --delete update-image-digest-${{ github.sha }}
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
   
